<?php

function glossary_theme($existing, $type, $theme, $path) {
  return [
    'glossary-listing' => [
      'variables' => [
        'content' => ['content' => NULL]
      ]
    ]
  ];
}
function glossary_preprocess_node(&$variables) {
  // Check if this is an article node (you can adjust the condition as needed).
  if ($variables['node']->getType() === 'article') {
    // Add the library to the page.
    $variables['#attached']['library'][] = 'glossary/glossary';
  }
}